### ISSUE TITLE
Chat Card Damage Application Not Working

### ISSUE THREAD

**Issue by AtreidesGhola** [WillNichols726/target-lock#6]
Tested with only Tidy UI and Target-Lock active.  The chat card still appears with the target listed and the damage buttons, but all buttons are inoperable, and will not apply any damage.

Foundry Version 9, Build 242
PF2E 3.2.1.10003

**Comment by Zadantur** [comment]
Not sure if this is related, but Target Lock was not working for me tonight. 
This happened after I updated both Foundry and PF2E.
Have attached a screenshot of what was appearing in the chat window.
None of the buttons for affecting the target were working and they were all mis-sized.
To inflict damage I had to target the intended recipient and then click on damage (or whatever  in the top row.
Also, I seem to remember items under templates being selected previously.  This is not working at all. 

Foundry Version 9 - Build 245
Pathfinder 3.2.2.1020
![TargetLock](https://user-images.githubusercontent.com/98561856/151457230-4f4c7cbe-d7f3-4dcf-86dc-b6b80baf8e78.png)
6

**Comment by Zadantur** [comment]
OK, a little digging, and I have fixed the non-application of damage when clicking the buttons for the target.
The issue is caused by the following line of code calling on a now non-existent file in the PF2E manifest.

`        const message = await renderTemplate('systems/pf2e/templates/chat/damage/result-message.html', {
            flavorText,
            by,
            messageSender,
            modifiedByGM,
            actor: token.name,
            shieldFlavor,
            appliedResult,
            hitpoints,
        });`

I have gotten around it by downloading a copy of the file from the previous release of PF2E and putting it in the module folder and editing the code to point at it. 
I'm guessing something similar is what has broken the formatting of the buttons, but I'm no HTML coder, so it may take me a little longer to chase it down.

**Comment by WillNichols726** [comment]
@Zadantur Thanks for looking into this. My development environment is still on 0.8.9 because I still have some content built out that I need to run for my players. My guess is that PF2e system has changed how damage is applied. Once I migrate to 0.9.x, I'll take another look at this repo.

**Comment by Zadantur** [comment]
@WillNichols726 The display problem is the way it's picking up the CSS from the PF2E module I suspect.
I tried pulling all the stuff from main.css into target-lock.css that seemed to be related to "chat-damage-buttons", and it did help a bit, but the formatting was still off.  Will limp along with it like that until you get a chance to take a look. Like I said, I'm more of a hack than a HTML coder. 

Other than my frustration at it not working, your module is one of my favourite add-ons for my PF2E game.  Being able to have the target listed in the damage window is a godsend.  :-)

**Comment by epfaffinger67** [comment]
This is still an issue. I agree this is awesome to see the targets listed in the chat window but when I click damage on one of the specific targets in the chat window the damage is not auto-applied (Red box in screen shot). I still  have to target the token and then click on the generic damage icon above all the listed targets (Green box in screen shot)? On Foundry 9.249
![image](https://user-images.githubusercontent.com/96535889/153032212-e874856c-7623-42c8-aba3-d5ea20f634cc.png)

**Comment by Zadantur** [comment]
> This is still an issue. I agree this is awesome to see the targets listed in the chat window but when I click damage on one of the specific targets in the chat window the damage is not auto-applied (Red box in screen shot). I still have to target the token and then click on the generic damage icon above all the listed targets (Green box in screen shot)? On Foundry 9.249 ![image](https://user-images.githubusercontent.com/96535889/153032212-e874856c-7623-42c8-aba3-d5ea20f634cc.png)

Strange that your display is still working right, wish mine was I've had to bodge the css to make it closer to normal, but if you unzip the attached file into the target-lock folder, it should get your buttons working again. Obviously take a backup of the module folder first ;-)
[Patch.zip](https://github.com/WillNichols726/target-lock/files/8031679/Patch.zip)

Hope that helps

Steve

**Comment by epfaffinger67** [comment]
@Zadantur Worked like a charm!!! This resolved my issue, thanks Steve!!!

**Comment by WillNichols726** [comment]
@Zadantur If you want to put a pull request together, I can merge it in as a temp patch for 0.9

**Comment by Zadantur** [comment]
> @Zadantur If you want to put a pull request together, I can merge it in as a temp patch for 0.9

Never done one before, but I'll look into it. 

Still no idea what is different between @epfaffinger67 setup and mine that is breaking the CSS.  Closest I've got is the following, which still isn't perfect, but better than my original post.
![image](https://user-images.githubusercontent.com/98561856/153225233-c51221a4-6c7d-4e51-8457-5b5eebc11b02.png)

which I did by bodging Target-lock.css like this.

> .target-lock-chat-window .chat-damage-buttons {   
>     margin-bottom: 5px;
> }
> .target-lock-chat-window .target-lock-target-name {
>     font-size: 12px;
> }
> 
> 
> 
> .chat-damage-buttons{display:flex;margin-top:3px}.message-content 
> .chat-damage-buttons button{flex:1 1 0;font-size:18px;line-height:.5em;position:relative;width:52px}.message-content 
> .chat-damage-buttons button>i.fas{left:1px;position:relative;top:1px;vertical-align:top}.message-content 
> .chat-damage-buttons button>.transparent-half{background:#eee;display:block;height:24px;left:48%;opacity:.6;position:absolute;top:0;width:16px}.message-content .chat-damage-buttons button .plus{color:ivory;font-size:17px;font-weight:700;left:40%;position:absolute;top:6px}.message-content 
> .chat-damage-buttons button>img{border:none;height:19px;position:relative;top:2px}.message-content 
> .chat-damage-buttons button .label{font-size:.4em;text-transform:uppercase}.message-content 
> .chat-damage-buttons.includes-fumble>button.triple-damage>img{left:-1px}.message-content 
> .chat-damage-buttons.includes-fumble span.plus{left:16px}.flavor-text 

but @epfaffinger67 didn't need to do this and theirs was fine.

**Comment by AtreidesGhola** [comment]
I tried using the patch posted above - it restores damage application, but I got the incorrectly sized buttons, which I didn't have previously.

**Comment by Zadantur** [comment]
> I tried using the patch posted above - it restores damage application, but I got the incorrectly sized buttons, which I didn't have previously.

The patch is at best a stopgap until Will advances his setup toward the current versions of PF2 and Foundry. My understanding of CSS is very rudimentary at best and it's a real bodge to only have mildly distorted buttons.

**Comment by gil4guirre** [comment]
I think this css code should solve the appearance issue temporarily. I've made it on the target-lock.css.


> .target-lock-chat-window .chat-damage-buttons {   
>     margin-top: 3px;
>     margin-bottom: 5px;
>     display: flex;
> }
> .target-lock-chat-window .target-lock-target-name {
>     font-size: 12px;
> }
> 
> .target-lock-chat-window .chat-damage-buttons button {  
>     width: 52px;
>     flex: 1 1 0;
>     font-size: 18px;
>     line-height: 0.5em;
>     position: relative;
> }
> 
> .target-lock-chat-window .chat-damage-buttons button .label{
>     font-size: .4em;
>     text-transform: uppercase;
>     
> }
> 
> .target-lock-chat-window .chat-damage-buttons button i.fas{
>     left: 1px;
>     position: relative;
>     top: 1px;
>     vertical-align: top;
> }
> 
> .target-lock-chat-window .chat-damage-buttons button img{
>     border: none;
>     height: 19px;
>     position: relative;
>     top: 2px;
> }
> 
> .target-lock-chat-window .chat-damage-buttons button .transparent-half{
>     background: #eee;
>     display: block;
>     height: 24px;
>     left: 48%;
>     opacity: .6;
>     position: absolute;
>     top: 0;
>     width: 16px;
> }
> 
> .target-lock-chat-window .chat-damage-buttons button .plus{
>     color: ivory;
>     font-size: 17px;
>     font-weight: 700;
>     left: 40%;
>     position: absolute;
>     top: 6px;
> }
